### ISSUE TITLE
DjangoPaddleBillingError when using standard /paddle/webhook handler

### ISSUE THREAD

**Issue by bndr** [websideproject/django-paddle-billing#155]
## 🐛 Bug Report

My Sentry is getting filled up with `DjangoPaddleBillingError` Duplicate errors on the standard `/paddle/webhook` View.  This has been happening from the start, and I decided to report it. There's currently something wrong with webhook processing.

Let me know if this something you will fix, or if I need to write my own webhook processing. This is happening with every payment a customer makes.

## 🔬 How To Reproduce

1. Use Paddle normally.

### Code sample

```Internal Server Error: /paddle/webhook/

DjangoPaddleBillingError at /paddle/webhook/
duplicate key value violates unique constraint "django_paddle_billing_subscription_pkey"
DETAIL:  Key (id)=(sub_01jf329ttXXXXXxz6ns8h) already exists.

Request Method: POST
Request URL: https://XXX/paddle/webhook/
Django Version: 4.2
Python Executable: /usr/local/bin/python
Python Version: 3.11.9
Python Path: ['/app', '/app', '/usr/local/bin', '/usr/local/lib/python311.zip', '/usr/local/lib/python3.11', '/usr/local/lib/python3.11/lib-dynload', '/usr/local/lib/python3.11/site-packages', '/usr/local/lib/python3.11/site-packages/setuptools/_vendor', '/app/XXXX']
Server time: Sat, 14 Dec 2024 17:08:49 +0000


Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(

  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/django/views.py", line 94, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_paddle_billing/views.py", line 100, in post
    signal.send(sender=self.__class__, payload=notification.data, occurred_at=notification.occurred_at)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [

  File "/usr/local/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/django/signals_handlers.py", line 73, in wrapper
    return receiver(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_paddle_billing/models.py", line 791, in subscription_event_handler
    raise DjangoPaddleBillingError(error)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: DjangoPaddleBillingError at /paddle/webhook/
Exception Value: duplicate key value violates unique constraint "django_paddle_billing_subscription_pkey"
DETAIL:  Key (id)=(sub_01jf329ttXXXXXXXXX6ns8h) already exists.

Raised during: django_paddle_billing.views.PaddleWebhookView```

### Environment

* OS: Linux
* Python version, get it with: 3.11

```bash
python --version
```

Let me know if you need any more context. Thanks a lot in advance.

**Comment by bgervan** [comment]
Hey, 

thanks for the report. From the exception, I am not sure what could go wrong. The from_paddle_data uses a custom update_or_create function. 

Which event type is it? 
Is the sandbox env? 
In Paddle: Developer tools -> Notifications menu, you can check the last events and it's responses on the webhook. Can you show me which events types fails and which successful? 

Does the sync_from_paddle command runs without issue?

Thanks.

**Comment by bgervan** [comment]
I have put together a small script:

```
import os
import django

# Set up Django
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "example.django_billing.django_billing.settings")
django.setup()

from django_paddle_billing.models import Subscription

data = Subscription.objects.first()

print(data)

defaults = {
    "customer_id": data.customer_id,
    "address_id": data.address_id,
    "business_id": data.business_id,
    "status": data.status,
    "data": data.data,
    "custom_data": data.custom_data,
}

_subscription, created = Subscription.update_or_create(
    query={"pk": data.id},
    defaults=defaults,
    occurred_at=data.occurred_at,
)

print(_subscription, created)
```

On your test environment you can run it. It should run without issue.

Which DB are you using?
