### ISSUE TITLE
ImportError: cannot import name 'HeaderAuthentication' from 'apiclient'

### ISSUE THREAD

**Issue by artemgordinskiy** [websideproject/django-paddle-billing#94]
## 🐛 Bug Report

Just installed the package and added to `INSTALLED_APPS`, and the app is now crashing:

```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python3.12/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "/usr/local/lib/python3.12/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.12/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.12/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/local/lib/python3.12/site-packages/django_paddle_billing/models.py", line 4, in <module>
    from apiclient import HeaderAuthentication
ImportError: cannot import name 'HeaderAuthentication' from 'apiclient' (/usr/local/lib/python3.12/site-packages/apiclient/__init__.py)
```

## 🔬 How To Reproduce

1. Install the package
2. Add to `INSTALLED_APPS`

### Environment

* OS: Linux (Docker)
* Python version: 3.12

Requirements:
```
api-client==0.1.2
    # via django-paddle-billing
asgiref==3.7.2
    # via
    #   channels
    #   channels-redis
    #   django
    #   django-cors-headers
    #   django-htmx
attrs==23.2.0
    # via
    #   aiohttp
    #   jsonschema
    #   referencing
django==5.0.7
    # via
    #   -r requirements/requirements.in
    #   channels
    #   django-allauth
    #   django-anymail
    #   django-celery-beat
    #   django-celery-results
    #   django-cors-headers
    #   django-hijack
    #   django-htmx
    #   django-otp
    #   django-paddle-billing
    #   django-redis
    #   django-storages
    #   django-timezone-field
    #   django-waffle
    #   djangorestframework
    #   drf-spectacular
django-allauth[mfa,socialaccount]==0.63.6
    # via -r requirements/requirements.in
django-anymail[brevo]==11.0.1
    # via -r requirements/requirements.in
django-cors-headers==4.4.0
    # via -r requirements/requirements.in
django-environ==0.11.2
    # via -r requirements/requirements.in
django-hijack==3.6.0
    # via -r requirements/requirements.in
django-htmx==1.18.0
    # via -r requirements/requirements.in
django-json-widget==2.0.1
    # via django-paddle-billing
django-otp==1.5.1
    # via -r requirements/requirements.in
django-paddle-billing==0.1.6
    # via -r requirements/requirements.in
django-redis==5.4.0
    # via -r requirements/requirements.in
django-storages==1.14.4
    # via -r requirements/requirements.in
django-timezone-field==6.1.0
    # via django-celery-beat
django-waffle==4.1.0
    # via -r requirements/requirements.in
djangorestframework==3.15.2
    # via
    #   -r requirements/requirements.in
    #   drf-spectacular
drf-spectacular==0.27.2
    # via -r requirements/requirements.in
kombu==5.3.5
    # via celery
python-crontab==3.0.0
    # via django-celery-beat
redis==5.0.1
    # via
    #   celery
    #   channels-redis
    #   django-redis
sqlparse==0.4.4
    # via django
tzdata==2023.4
    # via
    #   celery
    #   django-celery-beat
    #   pandas
vine==5.1.0
    # via
    #   amqp
    #   celery
    #   kombu
```

## 📎 Additional context

Does anyone have any idea what is the problem here?

**Comment by bgervan** [comment]
How did you install the package? I have just created a fresh venv (with python 3.12) and my api client version is

```
api-client==1.3.1
    # via api-client-pydantic
```

I ran simply pip install django-paddle-billing. Do you have a package which depends on that old version?

**Comment by artemgordinskiy** [comment]
I did a pip install, yeah.

```
$ pip install django-paddle-billing

Requirement already satisfied: django-paddle-billing in /usr/local/lib/python3.12/site-packages (0.1.6)
Requirement already satisfied: django-json-widget in /usr/local/lib/python3.12/site-packages (from django-paddle-billing) (2.0.1)
Requirement already satisfied: django>=4.2 in /usr/local/lib/python3.12/site-packages (from django-paddle-billing) (5.0.7)
Requirement already satisfied: paddle-billing-client>=0.2.4 in /usr/local/lib/python3.12/site-packages (from django-paddle-billing) (0.2.11)
Requirement already satisfied: asgiref<4,>=3.7.0 in /usr/local/lib/python3.12/site-packages (from django>=4.2->django-paddle-billing) (3.7.2)
Requirement already satisfied: sqlparse>=0.3.1 in /usr/local/lib/python3.12/site-packages (from django>=4.2->django-paddle-billing) (0.4.4)
Requirement already satisfied: api-client-pydantic<4.0.0,>=3.0.0 in /usr/local/lib/python3.12/site-packages (from paddle-billing-client>=0.2.4->django-paddle-billing) (3.0.0)
Requirement already satisfied: api-client>1.2.1 in /usr/local/lib/python3.12/site-packages (from api-client-pydantic<4.0.0,>=3.0.0->paddle-billing-client>=0.2.4->django-paddle-billing) (1.3.1)
Requirement already satisfied: pydantic<3.0,>=2.0 in /usr/local/lib/python3.12/site-packages (from api-client-pydantic<4.0.0,>=3.0.0->paddle-billing-client>=0.2.4->django-paddle-billing) (2.8.2)
Requirement already satisfied: requests>=2.16 in /usr/local/lib/python3.12/site-packages (from api-client>1.2.1->api-client-pydantic<4.0.0,>=3.0.0->paddle-billing-client>=0.2.4->django-paddle-billing) (2.32.3)
Requirement already satisfied: tenacity>=5.1.0 in /usr/local/lib/python3.12/site-packages (from api-client>1.2.1->api-client-pydantic<4.0.0,>=3.0.0->paddle-billing-client>=0.2.4->django-paddle-billing) (8.2.3)
Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.12/site-packages (from pydantic<3.0,>=2.0->api-client-pydantic<4.0.0,>=3.0.0->paddle-billing-client>=0.2.4->django-paddle-billing) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in /usr/local/lib/python3.12/site-packages (from pydantic<3.0,>=2.0->api-client-pydantic<4.0.0,>=3.0.0->paddle-billing-client>=0.2.4->django-paddle-billing) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in /usr/local/lib/python3.12/site-packages (from pydantic<3.0,>=2.0->api-client-pydantic<4.0.0,>=3.0.0->paddle-billing-client>=0.2.4->django-paddle-billing) (4.9.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.12/site-packages (from requests>=2.16->api-client>1.2.1->api-client-pydantic<4.0.0,>=3.0.0->paddle-billing-client>=0.2.4->django-paddle-billing) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/site-packages (from requests>=2.16->api-client>1.2.1->api-client-pydantic<4.0.0,>=3.0.0->paddle-billing-client>=0.2.4->django-paddle-billing) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/site-packages (from requests>=2.16->api-client>1.2.1->api-client-pydantic<4.0.0,>=3.0.0->paddle-billing-client>=0.2.4->django-paddle-billing) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/site-packages (from requests>=2.16->api-client>1.2.1->api-client-pydantic<4.0.0,>=3.0.0->paddle-billing-client>=0.2.4->django-paddle-billing) (2024.7.4)
```

> Do you have a package which depends on that old version?

Oh, my bad, I have `api-client` at `1.3.1` as well. 
I asked ChatGPT to remove the irrelevant packages from `requirements.txt` and it decided to change the version as well 😂

Thank you for the quick response!

**Comment by bgervan** [comment]
<img width="375" alt="image" src="https://github.com/user-attachments/assets/486c4ed4-8c15-4494-ab6f-86d7dd5d753a">
<img width="583" alt="image" src="https://github.com/user-attachments/assets/32bc56ca-c5c0-466f-b8d5-c9ee1d4b56fa">

What do you see here? Same version as me, but yours complains. My other guess would be an another package with the same folder name exists. Btw don't you use a venv? I see your system path, other projects can make a conflict easily. 

What is the full output for pip freeze?

**Comment by artemgordinskiy** [comment]
You're right! Looks like one of the [Google libs](https://github.com/googleapis/google-api-python-client/blob/main/apiclient/__init__.py) has claimed the `apiclient` name.
`site-packages/apiclient/__init__.py`

```python
"""Retain apiclient as an alias for googleapiclient."""

from googleapiclient import channel, discovery, errors, http, mimeparse, model

try:
    from googleapiclient import sample_tools
except ImportError:
    # Silently ignore, because the vast majority of consumers won't use it and
    # it has deep dependence on oauth2client, an optional dependency.
    sample_tools = None
from googleapiclient import schema

_SUBMODULES = {
    "channel": channel,
    "discovery": discovery,
    "errors": errors,
    "http": http,
    "mimeparse": mimeparse,
    "model": model,
    "sample_tools": sample_tools,
    "schema": schema,
}

import sys

for module_name, module in _SUBMODULES.items():
    sys.modules["apiclient.%s" % module_name] = module
```

> Btw don't you use a venv?

I use Docker, so venv shouldn't be necessary I think

**Comment by artemgordinskiy** [comment]
I'll close the issue since this isn't a bug with your library, but please let me know if you know any workarounds I could use here :)
